### ISSUE TITLE
MSVCR210.dll is missing - dll_hijack_test.exe

### ISSUE THREAD

**Issue by squirrelboot** [adamkramer/dll_hijack_detect#1]
"The program can't start because MSVCR120.dll is missing from your computer. Try reinstalling the program to fix this problem."

Windows 8.1

Wanted to run test before running dll_hijack_detect_x64.exe

**Comment by adamkramer** [comment]
Hey,

Sounds like you need the runtime libraries from Microsoft:

http://www.microsoft.com/en-gb/download/details.aspx?id=40784

Let me know how you get on,

Thanks,
Adam
