### ISSUE TITLE
Missing MSVCR120.dll Error in x64 Version

### ISSUE THREAD

**Issue by jstore** [adamkramer/dll_hijack_detect#2]
My system runs Win7 Pro 64 so I downloaded the x64 binary. When I try to launch it, it says, "The program can't start because MSVCR120.dll is missing from your computer. Try reinstalling the program to fix this problem" 

I then tried the x86 version and it did the same thing. I did a full search on my hard drive and found a copy of MSVCR120.dll from another app (Firefox). I copied the MSVCR120.dll from Firefox to the folder that I have both x86 and x64 binaries in. With the dll in place, the x86 version will launch but it doesn't find anything and exits almost immediately. The x64 version still doesn't run.

**Comment by adamkramer** [comment]
Hey, 

Sounds like you need the runtime libraries from Microsoft: http://www.microsoft.com/en-gb/download/details.aspx?id=40784 

Let me know how you get on, 

Thanks, 
Adam

**Comment by adamkramer** [comment]
(I'd try without the firefox one in the same dir though, once you've installed it from Microsoft, as they may be different)

**Comment by jstore** [comment]
Well, after installing the runtime libraries, the tool will launch, but the test exe returns the same missing dll error. So I copied the new MSVC120.dll from system32 into the same folder as the detect exe and the detect exe was able to detect itself running the local .dll. So, even though I couldn't get the test exe to run, I was able to verify that the detect exe is working by detecting itself.

**Comment by adamkramer** [comment]
Ah, that's great, I'm glad it works! :-)

I can't think why the test .exe would throw an error, when the main program isn't if they're looking for the same DLL hmm....If you have time, perhaps you could upload a cropped screenshot of the error message you see when you try and run the test program?

**Comment by jstore** [comment]
here you go. The first one is if run the test exe. The second is if i run
the test exe when a copy of MSVCR120.dll is in the same folder. The dll was
taken from system 32 after installing the runtime libraries.

**Comment by adamkramer** [comment]
Thanks :-) Unfortunately I can't see the image attached?

**Comment by jstore** [comment]
How about now? Before I had them embedded in the email. Now they are
attachments

**Comment by adamkramer** [comment]
Unfortunately not - I wonder whether attachments need to be done via the github website?

**Comment by jstore** [comment]
Can i just send them to you directly? my email is jrstore AT mtu DOT edu

**Comment by adamkramer** [comment]
Thanks to jstore for flagging this!

## For anyone else that reads / has the same problem

If you get error 0xc000007b from windows when trying to launch the test program, please let me know.
I suspect it has something to do with x86/x64 DLL conflict, but I'll dig deeper into it if required.

Fingers crossed it should work if you install the runtime libraries from:
http://www.microsoft.com/en-gb/download/details.aspx?id=40784

Thanks!

**Comment by g3rzi** [comment]
Hey Adam,

The links to the runtime libraries does'nt contain the download anymore.

**Comment by adamkramer** [comment]
Strange... hmm... what error do you get? Page loads ok for me?

________________________________

**Comment by g3rzi** [comment]
OK, it works. Maybe I entered the wrong link.
By the way, I ran the release files on Windows 10 x64 and received error about MSVCR120.dll.
I copied the code from the CPP and recompiled it and then it works fine.

**Comment by adamkramer** [comment]
Cool- thanks for letting me know

________________________________
